In [7]:
listOne = [1,2,3,4,5,6,7,8]
listTwo = [2,4,6,8,10,12,14,16]
a = []
b = []
print('Element at even-index position from listOne')
for i in range (0,len(listOne)):
    if i%2==0:
        a.append(listOne[i])
for i in range (0,len(listTwo)):
    if i%2==1:
        b.append(listTwo[i])
print(a)
print('Element at odd-index position from listTwo')
print(b)
print('Printing final third list')
a.extend(b)
print(a)

Element at even-index position from listOne
[1, 3, 5, 7]
Element at odd-index position from listTwo
[4, 8, 12, 16]
Printing final third list
[1, 3, 5, 7, 4, 8, 12, 16]


In [37]:
import numpy as np
randnums1 = np.random.randint(1,11,3)
randnums2 = np.random.randint(1,11,3)
randnums3 = np.random.randint(1,11,3)
randnums4 = np.random.randint(1,11,3)
randnums5 = randnums1 + randnums3
randnums6 = randnums2 + randnums4 
arrayOne = np.array([randnums1,randnums2],int)
print(format(arrayOne) + "= arrayOne")
arrayTwo = np.array([randnums3,randnums4],int)
print(format(arrayTwo) + "= arrayTwo")
arraySum = np.array([randnums5,randnums6],int)
arraySu\

[[3 3 1]
 [3 9 6]]= arrayOne
[[ 9  1  9]
 [ 5  2 10]]= arrayTwo


In [34]:
genre = ['111','222','333','444','555','666']
for i in range(0,len(genre)):
    if i%2 == 0:
        print('I like ' + genre[i])
    else:
        print('I don\'t like ' + genre[i])

I like 111
I don't like 222
I like 333
I don't like 444
I like 555
I don't like 666
